### ISSUE TITLE
Crossings that begin before "start race" can have negative value

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#37]
If a pass begins registering before the race begins but finishes after the race start, it can record a negative time value.

Ideally the start area is always outside the crossing zone, but in a noisy indoor environment it is not always possible.

All active crossings should be terminated and discarded at race start. Alternately, we could consider keeping these values but flagging them as false starts?

**Comment by ethomas997** [comment]
Have you seen this issue recently, and with the latest node code?  I thought I fixed it [here](https://github.com/RotorHazard/RotorHazard/commit/b97d7315996a98dd008d96bc7a3c1d1fe20f3c5f).

**Comment by HazardCreative** [comment]
Yes, I definitely saw it with the most recent nodes, as I was working with the pass-catch branch. I didn't see it all night, and then it happened with multiple pilots in the same heat at once, while another pilot read exactly zero. Might there be an issue with how the start time is transmitted to the nodes? Should there be delay compensation at that step?

**Comment by ethomas997** [comment]
Is there a set of steps that will reproduce this issue?

**Comment by HazardCreative** [comment]
I think this is related to having multiple clients open at once on the race page. Each race page is getting the staging signals and responding, resulting in multiple 'start race' signals. Each runs on_start_race again, resetting the race start time and re-marking node start times. However, laps may have started recording before the second call to on_race_start resets the start values.

**Comment by HazardCreative** [comment]
Not completely resolved be bd0a9e8, but I think this is the right track. Two clients trying to start a race at almost the same time can still cause issues with each other. Most likely another internal state is needed to track this process so multiple clients cannot interrupt it.

While fixing, an interrupted client must not prevent other clients from regaining control.
